### ISSUE TITLE
Colors look different between Terminal.app and Alacritty.

### ISSUE THREAD

**Issue by xfbs** [srcery-colors/srcery-terminal#12] opened 2019-05-21 15:37 UTC
So, I've setup both Terminal.app and Alacritty with the srcery colorscheme. And I noticed that the colors don't look identical. I took some screenshots to show this:

Terminal.app with Srcery colorscheme:
<img width="682" alt="terminal" src="https://user-images.githubusercontent.com/786420/58109577-2eda4480-7bee-11e9-8788-1f82d73bd709.png">

Alacritty with Srcery colorscheme:
<img width="682" alt="alacritty" src="https://user-images.githubusercontent.com/786420/58109572-2c77ea80-7bee-11e9-8f5a-5551839fa4b0.png">

I wasn't exactly sure why this would be. I checked the settings and confirmed that both are set correctly. For example, for the red color, Terminal.app is set to `#EF2F27`, and Alacritty is set to `0xEF2F27`. So that should be identical. But it's not. I had a hunch that it has something to do with color correction, so I used the Apple Digital Colour Meter to check.

Terminal.app renders Generic RGB 239, 47, 39.
<img width="486" alt="alacritty_color" src="https://user-images.githubusercontent.com/786420/58109735-719c1c80-7bee-11e9-9342-4c88bbc3a2c2.png">

Alacritty renders 239, 47, 39 as Display Native Value.
<img width="486" alt="terminal_color" src="https://user-images.githubusercontent.com/786420/58109725-6e089580-7bee-11e9-9a24-c6bfbe52672d.png">

This is why they look different, I'm guessing that Alacritty doesn't perform color correction. I'm not sure if that is a bug or a feature. But maybe the configs have to be adjusted slightly? I might manually perform color correction and pop the correct values into Alacritty so it's more consistent. Just leaving this here in case anyone else notices.

**Comment by roosta** [comment] 2019-05-22 09:19
Is there anything I can do with either Alacritty or Terminal.app conf? This seems to be an OS issue if what you describe is happening. Seems none of the colors when using Apple Digital Colour Meter are correct. If I check the Alacritty conf the color hexes are correct according to the srcery palette. I don't know exactly whats going on with the terminal.app config, it was generated using terminal.sexy using the same palette, but if you confirmed the hex values are correct it seems to be an issue with color correction

**Comment by xfbs** [comment] 2019-05-22 18:09
They are both correct, in a way: `#EF2F27 = rgb(239, 47, 39)`, and they both show 239, 47, 39 as color values. But one of them is interpreting that as a gRGB, and the other as a native RGB. I guess this is a bug with Alacritty (or Terminal.app?).

**Comment by MindTooth** [comment] 2019-05-22 18:15
Can this be of relevance https://github.com/jwilm/alacritty/issues/1485?

**Comment by mtklr** [comment] 2019-05-26 14:53
In Terminal.app, there's a gear icon in the color picker to select color profile. The built-in Terminal "themes" are set to "Device RGB", Srcery colors are set to "Generic RGB". Maybe changing the profile here will make the colors consistent?

![srcerycolors](https://user-images.githubusercontent.com/4858543/58383375-ffd42200-7fa3-11e9-95eb-bdb9c4b5c523.png)

**Comment by xfbs** [comment] 2019-05-27 16:27
Oh wow.. I didn't even notice that thing. That seems like a good remedy!

**Comment by roosta** [comment] 2019-05-28 16:01
Since this seems to be resolved, I'm closing this issue.

**Comment by MindTooth** [comment] 2020-04-26 10:21
Is your solution generic enough that we might upstream it?  How will it effect others?

**Comment by lulor** [comment] 2020-04-26 12:30
@MindTooth If you're referring to [this repo](https://github.com/lulor/srcery-terminal-app), unfortunately the profile is manually generated following the palette.
I didn't find any resource about creating a profile for Terminal.app using sRGB colours.

**Closed** 2022-11-17 13:58 UTC
